service: udemy-aws-lambda
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name
frameworkVersion: "3"

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs16.x
  region: ap-northeast-1

functions:
  first:
    handler: first.hello
  second:
    handler: second.hello
  hello:
    handler: src/hello.handler
  costNotifier:
    handler: src/costNotifier.handler
    events:
      # 日本時間で毎朝8時(標準時間から9時間ずれている)
      - schedule: cron(0 23 * * ? *)
    environment:
      SLACK_WEBHOOK_URL: ${ssm:UDEMY_AWS_LAMBDA_SLACK_WEBHOOK_URL}
