service: udemy-aws-lambda
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name
frameworkVersion: "3"

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs16.x
  region: ap-northeast-1

functions:
  first:
    handler: first.hello
  second:
    handler: second.hello
  hello: 
    handler: src/hello.handler
