service: udemy-aws-lambda
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name
frameworkVersion: "3"

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-iam-roles-per-function
  - serverless-api-gateway-throttling
custom:
  apiGatewayThrottling:
    maxRequestsPerSecond: 10 # 秒間10リクエスト
    maxConcurrentRequests: 5 # サーバーが同時に処理できるリクエスト数

provider:
  name: aws
  runtime: nodejs16.x
  region: ap-northeast-1

functions:
  first:
    handler: first.hello
  second:
    handler: second.hello
  hello:
    handler: src/hello.handler
    events:
      - httpApi:
          method: get
          path: /hello
  costNotifier:
    handler: src/costNotifier.handler
    events:
      # 日本時間で毎朝8時(標準時間から9時間ずれている)
      - schedule: cron(0 23 * * ? *)
    environment:
      SLACK_WEBHOOK_URL: ${ssm:UDEMY_AWS_LAMBDA_SLACK_WEBHOOK_URL}
    iamRoleStatements:
      - Effect: 'Allow'
        Action:
          - 'ce:GetCostAndUsage'
        Resource: '*'

resources:
  Resources:
    TasksDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: tasks
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
